default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root

development:
  <<: *default
  database: moods_dev

test:
  <<: *default
  database: moods_test

production:
  <<: *default
  database: moods_prod
